# Jekyll config
permalink: /:title:output_ext
strict_front_matter: true
liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# jekyll-feed
title: Chris Clark
description: "Read me!"
lang: en
